name: Release docker image

on:
  push:
    tags:
      - local
      - test
      - demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sets env vars for local
        run: |
          echo "DOCKER_IMAGE_NAME=conceptica/izadanky_fe_app:local" >> $GITHUB_ENV
          echo "REACT_APP_ROOT_API=${{ secrets.LOCAL_REACT_APP_ROOT_API }}" >> $GITHUB_ENV
          echo "REACT_APP_ROOT_FILES=${{ secrets.LOCAL_REACT_APP_ROOT_FILES }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/local')
      - name: Sets env vars for staging
        run: |
          echo "DOCKER_IMAGE_NAME=conceptica/izadanky_fe_app:test" >> $GITHUB_ENV
          echo "REACT_APP_ROOT_API=${{ secrets.TEST_REACT_APP_ROOT_API }}" >> $GITHUB_ENV
          echo "REACT_APP_ROOT_FILES=${{ secrets.TEST_REACT_APP_ROOT_FILES }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/test')
      - name: Sets env vars for release
        run: |
          echo "DOCKER_IMAGE_NAME=conceptica/izadanky_fe_app:demo" >> $GITHUB_ENV
          echo "REACT_APP_ROOT_API=${{ secrets.DEMO_REACT_APP_ROOT_API }}" >> $GITHUB_ENV
          echo "REACT_APP_ROOT_FILES=${{ secrets.DEMO_REACT_APP_ROOT_FILES }}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/demo')
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: ${{env.DOCKER_IMAGE_NAME}}
          build-args: |
            REACT_APP_ROOT_API=${{ env.REACT_APP_ROOT_API }}
            REACT_APP_ROOT_FILES=${{ env.REACT_APP_ROOT_FILES }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          ls -a /tmp/
